# Generated by Django 3.2.16 on 2023-01-17 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=511, verbose_name='Subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('document', models.FileField(blank=True, null=True, upload_to='notices', verbose_name='Document')),
            ],
        ),
    ]
