# Generated by Django 3.2.16 on 2023-01-17 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('is_present', models.BooleanField(default=False)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator.assign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
    ]
