# Generated by Django 3.2.16 on 2023-01-17 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='current_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_current_address', to='administrator.address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_permanent_address', to='administrator.address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.academicsession'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.course'),
        ),
        migrations.AddField(
            model_name='assign',
            name='assign_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='assign',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.subject'),
        ),
        migrations.AddField(
            model_name='assign',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.staff'),
        ),
        migrations.AddField(
            model_name='assign',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('batch', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('day', 'timeslot', 'teacher', 'assign_class')},
        ),
    ]
