# Generated by Django 3.2.16 on 2023-01-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student'),
        ),
        migrations.AddField(
            model_name='fee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
    ]
