from django.urls import path

from administrator.views import (
    create_academic_session_view,
    create_assign_view,
    create_class_view,
    create_course_view,
    create_department_view,
    create_subject_view,
    create_time_slot_view,
    delete_academic_session_view,
    delete_assign_view,
    delete_class_view,
    delete_course_view,
    delete_department_view,
    delete_subject_view,
    delete_time_slot_view,
    detail_academic_session_view,
    detail_assign_view,
    detail_class_view,
    detail_course_view,
    detail_department_view,
    detail_subject_view,
    detail_time_slot_view,
    home_view,
    list_academic_session_view,
    list_assign_view,
    list_class_view,
    list_course_view,
    list_department_view,
    list_subject_view,
    list_time_slot_view,
    update_academic_session_view,
    update_assign_view,
    update_class_view,
    update_course_view,
    update_department_view,
    update_subject_view,
    update_time_slot_view,
)
from administrator.views_staff import (
    create_staff_view,
    delete_staff_view,
    detail_staff_view,
    list_staff_view,
    password_change_view,
    profile_update_view,
    profile_view,
    update_staff_view,
)
from administrator.views_student import (
    create_student_view,
    delete_student_view,
    detail_student_view,
    list_student_view,
    update_student_view,
)

app_name = "administrator"

urlpatterns = [
    path("", home_view, name="home"),
    path("academic_session_add/", create_academic_session_view, name="academic-session-add"),
    path("academic_session_list/", list_academic_session_view, name="academic-session-list"),
    path("academic_session_detail/<uuid>/", detail_academic_session_view, name="academic-session-detail"),
    path("academic_session_update/<uuid>/", update_academic_session_view, name="academic-session-update"),
    path("academic_session_delete/<uuid>/", delete_academic_session_view, name="academic-session-delete"),
    path("department_add/", create_department_view, name="department-add"),
    path("department_list/", list_department_view, name="department-list"),
    path("department_detail/<uuid>/", detail_department_view, name="department-detail"),
    path("department_update/<uuid>/", update_department_view, name="department-update"),
    path("department_delete/<uuid>/", delete_department_view, name="department-delete"),
    path("course_add/", create_course_view, name="course-add"),
    path("course_list/", list_course_view, name="course-list"),
    path("course_detail/<uuid>/", detail_course_view, name="course-detail"),
    path("course_update/<uuid>/", update_course_view, name="course-update"),
    path("course_delete/<uuid>/", delete_course_view, name="course-delete"),
    path("class_add/", create_class_view, name="class-add"),
    path("class_list/", list_class_view, name="class-list"),
    path("class_detail/<uuid>/", detail_class_view, name="class-detail"),
    path("class_update/<uuid>/", update_class_view, name="class-update"),
    path("class_delete/<uuid>/", delete_class_view, name="class-delete"),
    path("subject_add/", create_subject_view, name="subject-add"),
    path("subject_list/", list_subject_view, name="subject-list"),
    path("subject_detail/<uuid>/", detail_subject_view, name="subject-detail"),
    path("subject_update/<uuid>/", update_subject_view, name="subject-update"),
    path("subject_delete/<uuid>/", delete_subject_view, name="subject-delete"),
    path("time_slot_add/", create_time_slot_view, name="time-slot-add"),
    path("time_slot_list/", list_time_slot_view, name="time-slot-list"),
    path("time_slot_detail/<uuid>/", detail_time_slot_view, name="time-slot-detail"),
    path("time_slot_update/<uuid>/", update_time_slot_view, name="time-slot-update"),
    path("time_slot_delete/<uuid>/", delete_time_slot_view, name="time-slot-delete"),
    path("assign_add/", create_assign_view, name="assign-add"),
    path("assign_list/", list_assign_view, name="assign-list"),
    path("assign_detail/<uuid>/", detail_assign_view, name="assign-detail"),
    path("assign_update/<uuid>/", update_assign_view, name="assign-update"),
    path("assign_delete/<uuid>/", delete_assign_view, name="assign-delete"),
    # Student Views
    path("student_add/", create_student_view, name="student-add"),
    path("student_list/", list_student_view, name="student-list"),
    path("student_detail/<uuid>/", detail_student_view, name="student-detail"),
    path("student_update/<uuid>/", update_student_view, name="student-update"),
    path("student_delete/<uuid>/", delete_student_view, name="student-delete"),
    # Staff Views
    path("staff_add/", create_staff_view, name="staff-add"),
    path("staff_list/", list_staff_view, name="staff-list"),
    path("staff_detail/<uuid>/", detail_staff_view, name="staff-detail"),
    path("staff_update/<uuid>/", update_staff_view, name="staff-update"),
    path("staff_delete/<uuid>/", delete_staff_view, name="staff-delete"),
    # Profile Views
    path("profile/", profile_view, name="profile"),
    path("profile_update/", profile_update_view, name="profile-update"),
    path("password_change/", password_change_view, name="password-change"),
]
